# Generated by Django 5.0.14 on 2026-08-08 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0004_statustrack_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('conduct', 'Conduct'), ('result', 'Result'), ('integrity', 'Integrity')], max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('evidence_url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_records', to=settings.AUTH_USER_MODEL)),
                ('exam_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_records', to='exams.examstage')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
