# Generated by Django 5.0.14 on 2026-08-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_historicalboard_historicalexam_historicalexamstage_and_more'),
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineObservationConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('conduct', 'Conduct'), ('result', 'Result'), ('integrity', 'Integrity')], max_length=20)),
                ('machine_value', models.CharField(max_length=50)),
                ('machine_confidence', models.FloatField(blank=True, null=True)),
                ('machine_seen_at', models.DateTimeField(blank=True, null=True)),
                ('human_value', models.CharField(max_length=50)),
                ('verified_by', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('exam_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_conflicts', to='exams.examstage')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
