# Generated by Django 5.0.14 on 2026-08-10 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examstage_admit_card_date_examstage_answer_key_date_and_more'),
        ('verification', '0002_machineobservationconflict'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.CharField(blank=True, max_length=50)),
                ('new_value', models.CharField(blank=True, max_length=50)),
                ('previous_confidence', models.FloatField(blank=True, null=True)),
                ('new_confidence', models.FloatField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('verification_task_id', models.CharField(blank=True, max_length=255)),
                ('needs_verification', models.BooleanField(blank=True, null=True)),
                ('queue_reason', models.CharField(blank=True, max_length=40)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='exams.statustrack')),
            ],
            options={
                'ordering': ['-detected_at', '-id'],
                'indexes': [models.Index(fields=['-detected_at'], name='verificatio_detecte_ddc868_idx'), models.Index(fields=['needs_verification', '-detected_at'], name='verificatio_needs_v_1f29d7_idx')],
            },
        ),
    ]
