# Generated by Django 5.0.14 on 2026-08-10 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_historicaldiscrepancy_discrepancy'),
        ('verification', '0003_statuschange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElapsedDateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.PositiveIntegerField(default=0)),
                ('exam_stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elapsed_date_alert', to='exams.examstage')),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
            },
        ),
    ]
