# Generated by Django 5.0.14 on 2026-08-08 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('cycle_year', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='exams.board')),
            ],
            options={
                'ordering': ['-cycle_year', 'board__name', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('board', 'code', 'cycle_year'), name='unique_exam_board_code_cycle_year'),
        ),
    ]
