# Generated by Django 5.0.14 on 2026-08-08 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_exam_unique_exam_board_code_cycle_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('prelims', 'Prelims'), ('mains', 'Mains'), ('interview', 'Interview'), ('skill', 'Skill'), ('single', 'Single')], max_length=20)),
                ('sequence', models.PositiveIntegerField()),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='exams.exam')),
            ],
            options={
                'ordering': ['exam', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='examstage',
            constraint=models.UniqueConstraint(fields=('exam', 'sequence'), name='unique_examstage_exam_sequence'),
        ),
    ]
