# Generated by Django 5.0.14 on 2026-08-08 07:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examstage_examstage_unique_examstage_exam_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('conduct', 'Conduct'), ('result', 'Result'), ('integrity', 'Integrity')], max_length=20)),
                ('machine_value', models.CharField(blank=True, max_length=50)),
                ('machine_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('machine_seen_at', models.DateTimeField(blank=True, null=True)),
                ('human_value', models.CharField(blank=True, max_length=50)),
                ('verified_by', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('exam_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_tracks', to='exams.examstage')),
            ],
            options={
                'ordering': ['exam_stage', 'track'],
            },
        ),
        migrations.AddConstraint(
            model_name='statustrack',
            constraint=models.UniqueConstraint(fields=('exam_stage', 'track'), name='unique_statustrack_exam_stage_track'),
        ),
    ]
