# Generated by Django 5.0.14 on 2026-08-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_historicalboard_historicalexam_historicalexamstage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstage',
            name='admit_card_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examstage',
            name='answer_key_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examstage',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examstage',
            name='notification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examstage',
            name='result_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalexamstage',
            name='admit_card_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalexamstage',
            name='answer_key_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalexamstage',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalexamstage',
            name='notification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalexamstage',
            name='result_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
