# Generated by Django 5.0.14 on 2026-08-10 09:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examstage_admit_card_date_examstage_answer_key_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDiscrepancy',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('discrepancy_type', models.CharField(choices=[('postponement', 'Postponement'), ('cancellation', 'Cancellation'), ('paper_leak', 'Paper leak'), ('key_error', 'Answer key error'), ('re_exam', 'Re-examination'), ('court_stay', 'Court stay'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('confirmed', 'Confirmed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='reported', max_length=15)),
                ('description', models.TextField()),
                ('evidence_url', models.URLField(blank=True, max_length=500)),
                ('evidence_note', models.TextField(blank=True)),
                ('occurred_on', models.DateField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('exam_stage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exams.examstage')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical discrepancy',
                'verbose_name_plural': 'historical discrepancies',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_type', models.CharField(choices=[('postponement', 'Postponement'), ('cancellation', 'Cancellation'), ('paper_leak', 'Paper leak'), ('key_error', 'Answer key error'), ('re_exam', 'Re-examination'), ('court_stay', 'Court stay'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('confirmed', 'Confirmed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='reported', max_length=15)),
                ('description', models.TextField()),
                ('evidence_url', models.URLField(blank=True, max_length=500)),
                ('evidence_note', models.TextField(blank=True)),
                ('occurred_on', models.DateField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('exam_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='exams.examstage')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_discrepancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'discrepancies',
                'ordering': ['-reported_at', '-id'],
                'indexes': [models.Index(fields=['status', '-reported_at'], name='exams_discr_status_ec0976_idx'), models.Index(fields=['exam_stage', 'status'], name='exams_discr_exam_st_a6b9b9_idx'), models.Index(fields=['discrepancy_type', '-reported_at'], name='exams_discr_discrep_85295c_idx')],
            },
        ),
    ]
