# Generated by Django 5.0.14 on 2026-08-09 06:40

import django.db.models.deletion
import scraping.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0006_examstage_admit_card_date_examstage_answer_key_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSource',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="Human label, e.g. 'UPSC notices'.", max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('fetch_strategy', models.CharField(choices=[('http', 'HTTP GET'), ('headless', 'Headless browser')], default='http', max_length=20)),
                ('parser_key', models.CharField(help_text="Key of the parser to use, e.g. 'upsc_notices'.", max_length=100)),
                ('cron', models.CharField(default='0 * * * *', help_text="Standard 5-field cron, e.g. '0 */6 * * *' for every six hours.", max_length=100, validators=[scraping.models.validate_cron])),
                ('enabled', models.BooleanField(default=True, help_text='Uncheck to stop scraping without deleting the config.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('board', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exams.board')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical source',
                'verbose_name_plural': 'historical sources',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human label, e.g. 'UPSC notices'.", max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('fetch_strategy', models.CharField(choices=[('http', 'HTTP GET'), ('headless', 'Headless browser')], default='http', max_length=20)),
                ('parser_key', models.CharField(help_text="Key of the parser to use, e.g. 'upsc_notices'.", max_length=100)),
                ('cron', models.CharField(default='0 * * * *', help_text="Standard 5-field cron, e.g. '0 */6 * * *' for every six hours.", max_length=100, validators=[scraping.models.validate_cron])),
                ('enabled', models.BooleanField(default=True, help_text='Uncheck to stop scraping without deleting the config.')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='exams.board')),
            ],
            options={
                'ordering': ['board__name', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('board', 'parser_key', 'url'), name='unique_source_board_parser_url'),
        ),
    ]
