# Generated by Django 5.0.14 on 2026-08-09 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('content', models.TextField()),
                ('status_code', models.PositiveSmallIntegerField()),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='scraping.source')),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['source', '-last_seen_at'], name='scraping_sn_source__b2d2bc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='snapshot',
            constraint=models.UniqueConstraint(fields=('source', 'content_hash'), name='unique_snapshot_source_content_hash'),
        ),
    ]
