# Generated by Django 5.0.14 on 2026-08-09 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_backfill_beat_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='scraping.source')),
            ],
            options={
                'verbose_name': 'source health',
                'verbose_name_plural': 'source health',
                'ordering': ['-consecutive_failures', 'source__name'],
            },
        ),
    ]
