# Generated by Django 5.0.14 on 2026-08-10 07:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examstage_admit_card_date_examstage_answer_key_date_and_more'),
        ('scraping', '0005_backfill_source_health'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTriageItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=500)),
                ('track', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('stage_hint', models.CharField(blank=True, max_length=100)),
                ('observed_date', models.DateField(blank=True, null=True)),
                ('parser_confidence', models.FloatField(default=1.0)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('raw_text', models.TextField(blank=True)),
                ('reason', models.CharField(choices=[('no_candidates', 'No exam matched'), ('below_threshold', 'Best match scored too low'), ('ambiguous', 'Two candidates scored too close'), ('no_stage', 'Matched an exam but not a stage')], max_length=30)),
                ('match_confidence', models.FloatField(default=0.0)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Needs triage'), ('linked', 'Linked to a stage'), ('created', 'New exam created'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('resolved_by', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('first_seen_at', models.DateTimeField(blank=True, editable=False)),
                ('last_seen_at', models.DateTimeField(blank=True, editable=False)),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('exam_stage', models.ForeignKey(blank=True, db_constraint=False, help_text='Set once an operator links or creates.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exams.examstage')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, db_constraint=False, help_text='Which source produced this. Kept if the source is later deleted.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scraping.source')),
            ],
            options={
                'verbose_name': 'historical triage item',
                'verbose_name_plural': 'historical triage items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TriageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=500)),
                ('track', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('stage_hint', models.CharField(blank=True, max_length=100)),
                ('observed_date', models.DateField(blank=True, null=True)),
                ('parser_confidence', models.FloatField(default=1.0)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('raw_text', models.TextField(blank=True)),
                ('reason', models.CharField(choices=[('no_candidates', 'No exam matched'), ('below_threshold', 'Best match scored too low'), ('ambiguous', 'Two candidates scored too close'), ('no_stage', 'Matched an exam but not a stage')], max_length=30)),
                ('match_confidence', models.FloatField(default=0.0)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Needs triage'), ('linked', 'Linked to a stage'), ('created', 'New exam created'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('resolved_by', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('exam_stage', models.ForeignKey(blank=True, help_text='Set once an operator links or creates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_items', to='exams.examstage')),
                ('source', models.ForeignKey(blank=True, help_text='Which source produced this. Kept if the source is later deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_items', to='scraping.source')),
            ],
            options={
                'ordering': ['status', '-times_seen', '-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['status', '-last_seen_at'], name='scraping_tr_status_4b24d1_idx'), models.Index(fields=['status', 'reason'], name='scraping_tr_status_0cd684_idx')],
            },
        ),
    ]
